name: UAT Stage

on:
  workflow_dispatch:

jobs:
  uat-release:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Generic System Release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const workflow = 'Generic System Release Stage';
            const response = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            });

            const workflow_id = response.data.workflows.find(w => w.name === workflow)?.id;

            if (!workflow_id) {
              throw new Error(`No workflow found with name: ${workflow}`);
            }

            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow_id,
              ref: context.ref,
            });

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Smoke Tests
        run: echo "Running smoke tests..." && npm run test

      - name: Run Curl Tests
        run: |
          echo "Checking if Task Manager is up..."
          curl -f http://${{ secrets.VM_IP }}:3001/health || exit 1
          echo "Checking if Title Generator is up..."
          curl -f http://${{ secrets.VM_IP }}:3002/health || exit 1

